# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: python_sdist_test

on:
  push:
    branches: [ master, dev/github_actions ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
          python-version: [3.5, 3.6, 3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Upgrade pip 
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements/build.txt
        python -m pip install -r requirements/tests.txt
    - name: Build sdist
      run: |
        python setup.py sdist
    - name: Install sdist
      run: |
        cd dist
        ls -al
        pip install line_profiler*.tar.gz -v
    - name: Test sdist
      run: |
        pwd
        ls -al
        # Ensure the source doesn't conflict with the test
        rm -rf line_profiler
        rm -rf kernprof.py  
        # cd ..
        python run_tests.py
